dist: trusty
sudo: false

language: node_js
node_js:
  - '12.16.3'


cache:
  directories:
    - ./node_modules

install:
  - npm install
  
script:
  - npm run lint && npm run test-prod && npm run build:ssr
  
  
